name: Auto deploy dev

on:
  push:
    branches: [ develop ]

jobs:
  Dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - uses: actions/checkout@v2
   
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: 74b5b90f-56b8-4b6e-b3e3-6b9c2ce805e0
        heroku_email: plazo1975@gmail.com
        heroku_app_name: demo-appi1-tst
        buildpack: https://github.com/jincod/dotnetcore-buildpack
        branch: develop
        dontuseforce: true
        dontautocreate: true
        usedocker: false
        docker_heroku_process_type: web
