name: prd-FLOW

on:
  workflow_dispatch

jobs:
  acc:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: Staging

    steps:
   
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: 74b5b90f-56b8-4b6e-b3e3-6b9c2ce805e0
        heroku_email: plazo1975@gmail.com
        heroku_app_name: demo-appi-acc
        buildpack: https://github.com/jincod/dotnetcore-buildpack
        branch: main
        dontuseforce: true
        dontautocreate: true
        usedocker: false
        docker_heroku_process_type: web
  prd:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: Staging
    needs: acc

    steps:
    - uses: actions/checkout@v2
   
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: 74b5b90f-56b8-4b6e-b3e3-6b9c2ce805e0
        heroku_email: plazo1975@gmail.com
        heroku_app_name: demo-appi-prd
        buildpack: https://github.com/jincod/dotnetcore-buildpack
        branch: main
        dontuseforce: true
        dontautocreate: true
        usedocker: false
        docker_heroku_process_type: web
